### ISSUE TITLE
Data must be a string or a buffer

### ISSUE THREAD

**Issue by eistrati** [TerraHubCorp/terrahub#242]
## Describe the Bug
Not sure what's happening, but `terrahub run` doesn't work

## Steps To Reproduce
```
$ thub run -i iam_authenticated
❌ Data must be a string or a buffer

$ ls -al
total 120
drwxr-xr-x  20 eugene  staff    680 Aug  7 10:51 .
drwxr-xr-x  81 eugene  staff   2754 Aug  6 19:12 ..
-rw-r--r--   1 eugene  staff    367 Aug  4 12:24 .codeclimate.yml
-rw-r--r--   1 eugene  staff    251 Aug  6 12:41 .eslintignore
-rw-r--r--   1 eugene  staff   4333 Aug  4 12:24 .eslintrc
drwxr-xr-x  15 eugene  staff    510 Aug  7 15:27 .git
-rw-r--r--   1 eugene  staff    562 Aug  6 10:41 .gitignore
-rw-r--r--   1 eugene  staff    812 Aug  4 12:24 .recink.yml
drwxr-xr-x  75 eugene  staff   2550 Aug  7 10:21 .terrahub
-rw-r--r--   1 eugene  staff     70 Aug  7 10:21 .terrahub.dev.yml
-rw-r--r--   1 eugene  staff     72 Aug  7 10:21 .terrahub.stage.yml
-rw-r--r--   1 eugene  staff     71 Aug  7 10:21 .terrahub.test.yml
-rw-r--r--   1 eugene  staff    195 Aug  7 11:04 .terrahub.yml
-rw-r--r--   1 eugene  staff  15896 Aug  4 12:24 LICENSE.md
-rw-r--r--   1 eugene  staff   1006 Aug  6 12:41 README.md
drwxr-xr-x   7 eugene  staff    238 Aug  6 10:41 bin
drwxr-xr-x   9 eugene  staff    306 Aug  6 18:36 docs
drwxr-xr-x   7 eugene  staff    238 Aug  7 11:04 lib
drwxr-xr-x   7 eugene  staff    238 Aug  4 12:24 src
drwxr-xr-x   6 eugene  staff    204 Aug  6 10:41 tests
```

## Expected Behavior
It should execute `terrahub run` without any errors

**Comment by Leichtwind** [comment]
@eistrati Can you please run this command with `DEBUG=debug` and send the log? It would help me a lot
I guess this bug is related to PR #239

**Comment by ddimitrioglo** [comment]
@Leichtwind looks like @eistrati uses `depends_on` instead of `dependsOn`

**Comment by eistrati** [comment]
```
$ DEBUG=debug thub run -i iam_authenticated
❌ TypeError: Data must be a string or a buffer
    at TypeError (native)
    at Hash.update (crypto.js:74:16)
    at toMd5 (/Volumes/Data/Users/eugene/Projects/hub/src/helpers/util.js:22:28)
    at Object.keys.forEach.hash (/Volumes/Data/Users/eugene/Projects/hub/src/helpers/util.js:105:19)
    at Array.forEach (native)
    at familyTree (/Volumes/Data/Users/eugene/Projects/hub/src/helpers/util.js:99:23)
    at RunCommand.getConfigTree (/Volumes/Data/Users/eugene/Projects/hub/src/terraform-command.js:148:12)
    at RunCommand.run (/Volumes/Data/Users/eugene/Projects/hub/src/commands/run.js:24:25)
    at command.validate.then (/Volumes/Data/Users/eugene/Projects/hub/bin/cli.js:50:23)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

**Comment by Leichtwind** [comment]
@eistrati Can you please show the content of `.terrahub.yml` of the `iam_authenticated`?

**Comment by eistrati** [comment]
```
$ cat .terrahub/iam_authenticated/.terrahub.yml 
## local config
component:
  name: 'iam_authenticated'
```

**Comment by eistrati** [comment]
@Leichtwind same thing if `depends_on` is defined
```
$ DEBUG=debug thub run -i s3_public,cloudfront_net
❌ TypeError: Data must be a string or a buffer
    at TypeError (native)
    at Hash.update (crypto.js:74:16)
    at toMd5 (/Volumes/Data/Users/eugene/Projects/hub/src/helpers/util.js:22:28)
    at Object.keys.forEach.hash (/Volumes/Data/Users/eugene/Projects/hub/src/helpers/util.js:105:19)
    at Array.forEach (native)
    at familyTree (/Volumes/Data/Users/eugene/Projects/hub/src/helpers/util.js:99:23)
    at RunCommand.getConfigTree (/Volumes/Data/Users/eugene/Projects/hub/src/terraform-command.js:148:12)
    at RunCommand.run (/Volumes/Data/Users/eugene/Projects/hub/src/commands/run.js:24:25)
    at command.validate.then (/Volumes/Data/Users/eugene/Projects/hub/bin/cli.js:50:23)
    at process._tickCallback (internal/process/next_tick.js:109:7)

$ cat .terrahub/s3_public/.terrahub.yml 
## local config
component:
  name: 's3_public'

$ cat .terrahub/cloudfront_net/.terrahub.yml 
## local config
component:
  name: 'cloudfront_net'
  depends_on:
    - '../s3_public'
```

**Comment by Leichtwind** [comment]
Thank you, this information helps me a lot
It should be `dependsOn` instead of `depends_on`

**Comment by eistrati** [comment]
In terraform, it's defined as `depends_on`, that's why I'm trying to change it ;)

**Comment by eistrati** [comment]
@Leichtwind @ddimitrioglo I've reverted back to `dependsOn` implementation and see the same issue
```
$ DEBUG=debug thub run -i s3_public,cloudfront_net
❌ TypeError: Data must be a string or a buffer
    at TypeError (native)
    at Hash.update (crypto.js:74:16)
    at toMd5 (/Volumes/Data/Users/eugene/Projects/hub/src/helpers/util.js:22:28)
    at Object.keys.forEach.hash (/Volumes/Data/Users/eugene/Projects/hub/src/helpers/util.js:105:19)
    at Array.forEach (native)
    at familyTree (/Volumes/Data/Users/eugene/Projects/hub/src/helpers/util.js:99:23)
    at RunCommand.getConfigTree (/Volumes/Data/Users/eugene/Projects/hub/src/terraform-command.js:148:12)
    at RunCommand.run (/Volumes/Data/Users/eugene/Projects/hub/src/commands/run.js:24:25)
    at command.validate.then (/Volumes/Data/Users/eugene/Projects/hub/bin/cli.js:50:23)
    at process._tickCallback (internal/process/next_tick.js:109:7)

$ cat .terrahub/cloudfront_net/.terrahub.yml 
## local config
component:
  name: 'cloudfront_net'
  dependsOn:
    - '../s3_public'
```
