### ISSUE TITLE
❌ TypeError: Cannot convert undefined or null to object when running `thub component` command

### ISSUE THREAD

**Issue by avozicov** [TerraHubCorp/terrahub#488]
## Bug Report
- I am facing issue with [`terrahub component -t $AWS_TEMPLATE -n $AWS_COMPONENT -e $ENVIRONMENT] wren trying to [create terrahub template for aws_s3_bucket]

## Steps to Reproduce
```
aws-saml login --alias CloudNativeCI

THUB_API=api-$ENVIRONMENT THUB_TOKEN=$THUB_TOKEN_DEV terrahub project -n $AWS_PROJECT -d ./projects/$AWS_PROJECT

cd ./projects/$AWS_PROJECT
terrahub component -t $AWS_TEMPLATE -n $AWS_COMPONENT -e $ENVIRONMENT

THUB_API=api-$ENVIRONMENT THUB_TOKEN=$THUB_TOKEN_DEV terrahub run -$1 -y --var=account_id:$AWS_ACCOUNT_ID
```

## Expected Behavior
- TerraHub Project dir should be created and contain template for aws_s3_bucket

## Actual Behavior
- The following error message is displayed:
```
💡 Project already configured in /Users/alexandrvozicov/Projects/automation-testing/terrahub-cli/projects/QA_AWS_Project directory
❌ TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at ComponentCommand._getTemplatePath (/Users/alexandrvozicov/.nvm/versions/node/v8.14.0/lib/node_modules/terrahub/src/commands/component.js:244:17)
    at ComponentCommand._createNewComponent (/Users/alexandrvozicov/.nvm/versions/node/v8.14.0/lib/node_modules/terrahub/src/commands/component.js:174:31)
    at Promise.all.names.map.it (/Users/alexandrvozicov/.nvm/versions/node/v8.14.0/lib/node_modules/terrahub/src/commands/component.js:67:47)
    at Array.map (<anonymous>)
    at ComponentCommand.run (/Users/alexandrvozicov/.nvm/versions/node/v8.14.0/lib/node_modules/terrahub/src/commands/component.js:67:32)
    at command.validate.then (/Users/alexandrvozicov/.nvm/versions/node/v8.14.0/lib/node_modules/terrahub/bin/cli.js:50:23)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
    at Function.Module.runMain (module.js:696:11)
```

## Additional Context
- TerraHub CLI Version: `terrahub@alpha v0.0.58`
- TerraHub API: `https://api-test.terrahub.io/v1`

**Comment by ddimitrioglo** [comment]
@avozicov could you please decode your environment variables: `$ENVIRONMENT`, `$AWS_PROJECT` &  `$AWS_COMPONENT`, it's very important at this point

**Comment by avozicov** [comment]
@ddimitrioglo 
`$ENVIRONMENT` = `test`
`$AWS_PROJECT` = `QA_AWS_Project`
`$AWS_COMPONENT` = `qa-terrahub-s3-bucket`

**Comment by ddimitrioglo** [comment]
@avozicov and `$AWS_TEMPLATE` please

**Comment by avozicov** [comment]
@ddimitrioglo Did not faced this issue with latest code from dev for `cli + api` so I am marked as resolved

Tested with google provider ;)

<img width="1440" alt="screen shot 2018-12-11 at 17 32 29" src="https://user-images.githubusercontent.com/12330493/49810875-c9df1080-fd6a-11e8-80f0-0bbcd416e710.png">

**Comment by eistrati** [comment]
Checked.
