### ISSUE TITLE
Component: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by euliancom** [TerraHubCorp/terrahub#617]
I am facing error when trying to execute `terrahub component -n test -d ./test` command for any new components without templates

Log:
```
❌ TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.dirname (path.js:1346:5)
    at terraform.workspaceList.then.catch.then (/mnt/c/Terrahub/terrahub/src/commands/component.js:225:51)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
```

**Comment by avozicov** [comment]
Fixed.
Required to be released in production.

<img width="897" alt="Screen Shot 2019-03-11 at 2 41 28 PM" src="https://user-images.githubusercontent.com/12330493/54124710-d0356500-440b-11e9-86db-71c0cef7dd1b.png">

**Comment by eistrati** [comment]
Checked.
