### ISSUE TITLE
Validate THUB_TOKEN before execution terrahub run --cloud option

### ISSUE THREAD

**Issue by avozicov** [TerraHubCorp/terrahub#671]
<img width="707" alt="Screen Shot 2019-04-12 at 3 12 31 PM" src="https://user-images.githubusercontent.com/12330493/56036387-6aebd100-5d35-11e9-9120-093ca469642c.png">

**Comment by Leichtwind** [comment]
Expected behavior:
1. before `run --cloud` execution terrahub makes a call to terrahub-api to retrieve user's permissions
2. if user is not allowed to execute `run --cloud` execution is interrupted with an error

**Comment by avozicov** [comment]
@const-andreyLu 

We need to improve use case for `run --cloud` without THUB_TOKEN
```
Alexandrs-MacBook-Pro:terrahub-project alexandrvozicov$ terrahub run --cloud
/Users/alexandrvozicov/Work/terrahub/src/commands/run.js:157
      throw new Error('Please provide valid THUB_TOKEN');
      ^

Error: Please provide valid THUB_TOKEN
    at RunCommand.onTokenMissingOrInvalid (/Users/alexandrvozicov/Work/terrahub/src/commands/run.js:157:13)
    at RunCommand.validateToken (/Users/alexandrvozicov/Work/terrahub/src/abstract-command.js:275:12)
    at RunCommand.validate (/Users/alexandrvozicov/Work/terrahub/src/abstract-command.js:171:17)
    at RunCommand.validate (/Users/alexandrvozicov/Work/terrahub/src/terraform-command.js:41:18)
    at Object.<anonymous> (/Users/alexandrvozicov/Work/terrahub/bin/cli.js:49:4)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
Alexandrs-MacBook-Pro:terrahub-project alexandrvozicov$ 
```

**Comment by avozicov** [comment]
This is implemented and released in

**Comment by eistrati** [comment]
Checked.
