### ISSUE TITLE
TypeError: Cannot match against 'undefined' or 'null' in jit-helper.js:55

### ISSUE THREAD

**Issue by eistrati** [TerraHubCorp/terrahub#767]
## Describe the Bug

TypeError: Cannot match against 'undefined' or 'null' in jit-helper.js:55

## To Reproduce

```
terrahub project -n terrahub-project -d ./terrahub-project && cd ./terrahub-project
terrahub component -t aws_ssm_parameter -n terrahub-component-first
terrahub workspace -e test
```

## Expected Behavior

I should NOT have code errors

## Screenshots

```
$ terrahub workspace -e test
💡 THUB_TOKEN is not provided.
Project: terrahub-project
 └─ terrahub-component-first
💡 'terrahub workspace' action is executed for above list of components.
/Volumes/Data/Users/eugene/Projects/hub/src/helpers/jit-helper.js:55
    const { terraform: { backend: { local } } } = template;
                                                  ^

TypeError: Cannot match against 'undefined' or 'null'.
    at Function._normalizeBackendLocalPath (/Volumes/Data/Users/eugene/Projects/hub/src/helpers/jit-helper.js:55:51)
    at Function._transformConfig (/Volumes/Data/Users/eugene/Projects/hub/src/helpers/jit-helper.js:25:42)
    at Function.jitMiddleware (/Volumes/Data/Users/eugene/Projects/hub/src/helpers/jit-helper.js:119:41)
    at process.run (/Volumes/Data/Users/eugene/Projects/hub/src/helpers/distributors/worker.js:35:13)
    at emitTwo (events.js:111:20)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:758:12)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
✅ TerraHub environment 'test' was created
```

**Comment by eistrati** [comment]
Checked.
