### ISSUE TITLE
EEXIST: file already exists, mkdir '/var/lib/jenkins/.terrahub/cache/jit/api_gateway_rest_api_807a087b/workspace'

### ISSUE THREAD

**Issue by eistrati** [TerraHubCorp/terrahub#793]
## Describe the Bug

EEXIST: file already exists, mkdir '/var/lib/jenkins/.terrahub/cache/jit/api_gateway_rest_api_807a087b/workspace'

## To Reproduce

1. Go to Jenkins server: job/mitocgroup-www-ba/118/console
2. Setup `BRANCH_FROM="dev"` and `BRANCH_TO="master"`

## Expected Behavior

I expected no issues, but got the following:
```
💡 [api_gateway_domain_name] terraform init -no-color -force-copy -input=false .
[api_gateway_domain_name] 
[api_gateway_domain_name] Initializing the backend...
❌ Error: Worker error: "EEXIST: file already exists, mkdir '/var/lib/jenkins/.terrahub/cache/jit/api_gateway_rest_api_807a087b/workspace'"
    at ThreadDistributor._handleError (/mnt/data/jenkins/terrahub/src/helpers/distributors/thread-distributor.js:133:48)
    at EventEmitter.cluster.on (/mnt/data/jenkins/terrahub/src/helpers/distributors/thread-distributor.js:87:30)
    at emitThree (events.js:136:13)
    at EventEmitter.emit (events.js:217:7)
    at Worker.<anonymous> (internal/cluster/master.js:169:13)
    at emitTwo (events.js:126:13)
    at Worker.emit (events.js:214:7)
    at ChildProcess.Worker.process.on (internal/cluster/worker.js:42:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
Build step 'Execute shell' marked build as failure
```

**Comment by eistrati** [comment]
Never mind. Looks like the problem was related to bad syntax in `.terrahub.yml` ...
```
component:
    tfvars:
      api_gateway_name: BaMasterApi807a087b
```

Correct syntax was supposed to be:
```
component:
  template:
    tfvars:
      api_gateway_name: BaMasterApi807a087b
```
