### ISSUE TITLE
Error when executing `terrahub configure` command

### ISSUE THREAD

**Issue by eistrati** [TerraHubCorp/terrahub#802]
## Describe the Bug

Error when executing `terrahub configure` command ...
```
✅ Done 
Error: Error occurred. Please try again. If this problem persists, enable extra debugging (DEBUG=debug) to see more details and open an issue at https://github.com/TerraHubCorp/terrahub/issues
    at result.json.then.json (/mnt/data/jenkins/terrahub/src/helpers/fetch.js:84:19)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

## To Reproduce

1. Go to https://github.com/TerraHubCorp/terraform-automation-demo-aws
2. Open PR from dev to master (DON'T merge)
3. Check logs in CodeBuild to see errors while executing `./bin/backend-remote.sh`

**Comment by eistrati** [comment]
Checked.
