### ISSUE TITLE
ResponseError: index_not_found_exception

### ISSUE THREAD

**Issue by eistrati** [TerraHubCorp/terrahub#804]
## Describe the Bug

ResponseError: index_not_found_exception

## To Reproduce

Go to Jenkins, URI `/job/mitocgroup-www-ba/188/console`

## Expected Behavior

```
{ stack: 'ResponseError: index_not_found_exception
    at IncomingMessage.response.on (/opt/nodejs/node_modules/lib-thub/index.js:64790:25)
    at emitNone (events.js:111:20)\n    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at /opt/nodejs/node_modules/lib-thub/index.js:33093:31
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback [as _tickCallback] (internal/process/next_tick.js:218:9)',
  message: 'index_not_found_exception',
  errorType: 'NotFoundException',
  statusCode: 404 }
```

**Comment by eistrati** [comment]
Checked.
