### ISSUE TITLE
RequestError: send request failed caused by: Get https://data-lake-terrahub-us-east-1.s3.amazonaws.com/?prefix=terraform_workspaces: connection refused

### ISSUE THREAD

**Issue by eistrati** [TerraHubCorp/terrahub#811]
## Describe the Bug
RequestError: send request failed caused by: Get https://data-lake-terrahub-us-east-1.s3.amazonaws.com/?prefix=terraform_workspaces: connection refused

## Steps to Reproduce
1. Go to Jenkins
2. Select project `terrahub-api`
3. Find logs for job #2445

## Expected Behavior

```
❌ [lambda_thub_variables_retrieve] [31mRequestError: send request failed
caused by: Get https://data-lake-terrahub-us-east-1.s3.amazonaws.com/?prefix=terraform_workspaces%2F: dial tcp: lookup data-lake-terrahub-us-east-1.s3.amazonaws.com on 127.0.0.53:53: read udp 127.0.0.1:59717->127.0.0.53:53: read: connection refused[0m[0m

FetchError: Internet connection issue
    at ClientRequest.<anonymous> (/mnt/data/jenkins/terrahub/node_modules/node-fetch/lib/index.js:1455:11)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

**Comment by eistrati** [comment]
This problem still persists (jenkins, project terrahub-api, job #2500):
```
❌ [lambda_thub_listing_count] Error refreshing state: RequestError: send request failed

❌ [lambda_thub_listing_count] caused by: Get https://data-lake-terrahub-us-east-1.s3.amazonaws.com/terraform_workspaces/test/terraform/mitocgroup/terrahub-api/lambda_thub_listing_count/terraform.tfstate: read tcp 172.31.20.196:37398->52.216.184.35:443: read: connection reset by peer
```

**Comment by eistrati** [comment]
Checked.
