### ISSUE TITLE
Error: There are no changes between commits, commit and working tree, etc.

### ISSUE THREAD

**Issue by eistrati** [TerraHubCorp/terrahub#817]
## Describe the Bug
Error: There are no changes between commits, commit and working tree, etc.

## To Reproduce
```
EXEC: terrahub run -y  -e test -g test..dev -b -a -I '^([a-z])' -X '^(lambda_proxy|sfn|vpc|subnet|security|route_table|internet|nat|code|elasticsearch|route53|.*cloudtrail.*|s3_cloudtrail_event|db_subnet_group)'
❌ Error: There are no changes between commits, commit and working tree, etc.
    at Function.getGitDiff (/mnt/data/jenkins/terrahub/src/helpers/git-helper.js:43:13)
    at RunCommand.getGitDiff (/mnt/data/jenkins/terrahub/src/terraform-command.js:275:32)
    at RunCommand.getFilteredConfig (/mnt/data/jenkins/terrahub/src/terraform-command.js:210:26)
    at RunCommand.run (/mnt/data/jenkins/terrahub/src/commands/run.js:34:25)
    at command.validate.then.then (/mnt/data/jenkins/terrahub/bin/cli.js:76:23)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

## Expected Behavior
Instead of throwing an error, please change this behavior to show an warning, AND continue executing `terrahub run` for ALL components

**Comment by eistrati** [comment]
Checked.
