### ISSUE TITLE
Failed to load backend: This plan was created against an older state than is current

### ISSUE THREAD

**Issue by eistrati** [TerraHubCorp/terrahub#828]
## Describe the Bug

Failed to load backend: This plan was created against an older state than is current

## To Reproduce

```
❌ [lambda_github_repo_retrieve] Failed to load backend: This plan was created against an older state than is current. Please create

❌ [lambda_github_repo_retrieve] a new plan file against the latest state and try again.

Terraform doesn't allow you to run plans that were created from older

❌ [lambda_github_repo_retrieve] states since it doesn't properly represent the latest changes Terraform
may have made, and can result in unsafe behavior.

Plan Serial:    479

❌ [lambda_github_repo_retrieve] Current Serial: 481

❌ Worker error: Failed to load backend: This plan was created against an older state than is current. Please create
a new plan file against the latest state and try again.

Terraform doesn't allow you to run plans that were created from older
states since it doesn't properly represent the latest changes Terraform
may have made, and can result in unsafe behavior.

Plan Serial:    479
Current Serial: 481

MitocGroup:hub-api eugene$ 
(node:20866) UnhandledPromiseRejectionWarning: Error [ERR_IPC_CHANNEL_CLOSED]: channel closed
    at process.target.send (internal/child_process.js:588:16)
    at JitHelper.jitMiddleware.then.then.catch.error (/Volumes/Data/Users/eugene/Projects/hub/src/helpers/distributors/worker.js:62:15)
    at <anonymous>
(node:20866) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:20866) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[lambda_github_repo_configure] Refreshing Terraform state in-memory prior to plan...
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error [ERR_IPC_CHANNEL_CLOSED]: channel closed
    at process.target.send (internal/child_process.js:588:16)
    at Logger._sendMessageToMaster (/Volumes/Data/Users/eugene/Projects/hub/src/helpers/logger.js:123:13)
    at Logger._sendLogToApi (/Volumes/Data/Users/eugene/Projects/hub/src/helpers/logger.js:111:12)
    at Logger.raw (/Volumes/Data/Users/eugene/Projects/hub/src/helpers/logger.js:46:12)
    at data (/Volumes/Data/Users/eugene/Projects/hub/src/helpers/wrappers/terraform.js:427:18)
    at Socket.childProcess.stdout.on.data (/Volumes/Data/Users/eugene/Projects/hub/src/helpers/util.js:231:7)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
[lambda_thub_continuous_delivery_retrieve] Refreshing Terraform state in-memory prior to plan...
events.js:183
      throw er; // Unhandled 'error' event
```

**Comment by eistrati** [comment]
@const-andreyLu if you are not able to reproduce this issue, at least figure out how to `catch` this exception, so it doesn't look ugly next time when we're coming across it ;)

**Comment by eistrati** [comment]
```
module.landing_zone.null_resource.landing_zone_apply (local-exec): ❌ Worker error: 2019/07/23 08:33:44 [INFO] Terraform version: 0.11.11  ac4fff416318bf0915a0ab80e062a99ef3724334
module.landing_zone.null_resource.landing_zone_apply (local-exec): 2019/07/23 08:33:44 [INFO] Go runtime version: go1.11.1
module.landing_zone.null_resource.landing_zone_apply (local-exec): 2019/07/23 08:33:44 [INFO] CLI args: []string{"terraform", "apply", "-no-color", "-backup=.backup/tfstate/terraform.tfstate.1563885224431.backup", "-auto-approve=true", "-input=false", ".terrahub/cache/jit/landing_zone_route_table_eef16dcf/terraform.tfplan"}
module.landing_zone.null_resource.landing_zone_apply (local-exec): 2019/07/23 08:33:44 [DEBUG] Attempting to open CLI config file: .terraformrc
module.landing_zone.null_resource.landing_zone_apply (local-exec): 2019/07/23 08:33:44 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
module.landing_zone.null_resource.landing_zone_apply (local-exec): 2019/07/23 08:33:44 [INFO] CLI command args: []string{"apply", "-no-color", "-backup=.backup/tfstate/terraform.tfstate.1563885224431.backup", "-auto-approve=true", "-input=false", ".terrahub/cache/jit/landing_zone_route_table_eef16dcf/terraform.tfplan"}
module.landing_zone.null_resource.landing_zone_apply (local-exec): 2019/07/23 08:33:44 [INFO] command: initializing backend from plan: local
module.landing_zone.null_resource.landing_zone_apply (local-exec): 2019/07/23 08:33:44 [TRACE] Preserving existing state lineage "4d59775f-fde3-7635-344a-972a5d07f3e2"
module.landing_zone.null_resource.landing_zone_apply (local-exec): 2019/07/23 08:33:44 [TRACE] Preserving existing state lineage "4d59775f-fde3-7635-344a-972a5d07f3e2"
module.landing_zone.null_resource.landing_zone_apply (local-exec): 2019/07/23 08:33:44 [DEBUG] plugin: waiting for all plugin processes to complete...


module.landing_zone.null_resource.landing_zone_apply (local-exec):     at Helper.cli (terraform-aws-landing-zone/modules/landing_zone/scripts/helper.js:23:27)
module.landing_zone.null_resource.landing_zone_apply (local-exec):     at argsList.reduce (terraform-aws-landing-zone/modules/landing_zone/scripts/helper.js:51:21)
module.landing_zone.null_resource.landing_zone_apply (local-exec):     at <anonymous>
module.landing_zone.null_resource.landing_zone_apply (local-exec):     at process._tickCallback (internal/process/next_tick.js:188:7)
module.landing_zone.null_resource.landing_zone_apply (local-exec):     at Function.Module.runMain (module.js:695:11)
module.landing_zone.null_resource.landing_zone_apply (local-exec):     at startup (bootstrap_node.js:188:16)
module.landing_zone.null_resource.landing_zone_apply (local-exec):     at bootstrap_node.js:609:3
module.landing_zone.null_resource.landing_zone_apply (local-exec): (node:82023) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
module.landing_zone.null_resource.landing_zone_apply (local-exec): (node:82023) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by eistrati** [comment]
Checked.
