### ISSUE TITLE
Remove `workspace` folder from path for non-default `.tfvars` files

### ISSUE THREAD

**Issue by eistrati** [TerraHubCorp/terrahub#910]
## Describe the Bug
Remove `workspace` folder from path for non-default `.tfvars` files

## To Reproduce
Currently, if I move `master.tfvars` away from `workspace/` folder, I get the following error:
```
❌ Error: Worker error: Unexpected token } in JSON at position 518
    at ThreadDistributor._handleError ([REDACTED]/Projects/hub/src/helpers/distributors/thread-distributor.js:208:48)
    at EventEmitter.cluster.on ([REDACTED]/Projects/hub/src/helpers/distributors/thread-distributor.js:122:30)
    at emitThree (events.js:136:13)
    at EventEmitter.emit (events.js:217:7)
    at Worker.<anonymous> (internal/cluster/master.js:169:13)
    at emitTwo (events.js:126:13)
    at Worker.emit (events.js:214:7)
    at ChildProcess.Worker.process.on (internal/cluster/worker.js:42:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
```

## Expected Behavior
Default path for any workspace should be component's current working directory. Unless otherwise specified in `.terrahub.yml`, we should assume `master.tfvars` or `testing.tfvars` (or any other `.tfvars` file corresponding to associated terraform workspace) is not stored in any extra folders.

**Comment by eistrati** [comment]
Checked.
